---
deployment:
  targets:
    production:
      type: web
      default: true
      domain: kiranoglu.net
      path: /home/kiranoglu/muhasebe
      exclude_paths:
        - .git
        - .gitignore
        - README.md
        - node_modules
